-- Your SQL goes here
CREATE TYPE USER_TYPE AS ENUM ('admin' , 'user');

-- ADDING FUNCTIONALITY ,SO THAT SQL CAN GENRATE RANDOM UUID'S
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "users" (
    id UUID NOT NULL PRIMARY KEY DEFAULT (uuid_generate_V4()),
    name VARCHAR(100) NOT NULL ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    verified BOOLEAN NOT NULL DEFAULT FALSE ,
    password VARCHAR(100) NOT NULL ,
    verification_token VARCHAR(255),
    token_expires_at TIMESTAMP WITH TIME ZONE ,
    role USER_TYPE NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()

);

-- CREATING INDEX DATA STRUCTURE , SO THAT WE CAN SEARCH FAST
CREATE INDEX user_email_idx ON users (email);