use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use diesel_derive_enum::DbEnum;

// Bring in the table generated by Diesel:
// NOT from db::users — only from schema::users!
use crate::schema::{user_email_verifications, user_reset_pass_validations, users};

// Bring in the SQL type Diesel generated:
use crate::schema::sql_types::UserType;

// This enum will map to your Postgres enum
#[derive(DbEnum, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[ExistingTypePath = "UserType"]
pub enum UserRole {
    #[db_rename = "admin"]
    Admin,
    #[db_rename = "user"]
    User,
}

// Now your User struct works
#[derive(Queryable, QueryableByName, Selectable, Serialize, Deserialize, Debug, Clone)]
#[diesel(table_name = users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Users {
    pub id: Uuid,
    pub name: String,
    pub email: String,
    pub verified: bool,
    pub password: String,
    pub verification_token: Option<String>,
    pub token_expires_at: Option<DateTime<Utc>>,
    pub role: UserRole,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

#[derive(Queryable, QueryableByName, Selectable, Serialize, Deserialize, Debug, Clone)]
#[diesel(table_name = user_email_verifications)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserEmailVerifications {
    pub id: Uuid,
    pub user_email: String,
    pub otp: String,
    pub expires_at: Option<DateTime<Utc>>,
    pub used: bool,
}

#[derive(Queryable , QueryableByName , Selectable , Serialize , Deserialize , Debug , Clone)]
#[diesel(table_name = user_reset_pass_validations)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserResetPasswordValidations {
    pub id : Uuid,
    pub user_email : String,
    pub hashed_reset_token : String,
    pub expires_at : Option<DateTime<Utc>>,
    pub used : bool
}


// if we want to add data to the db tables , we have to crete new* sturct for db table with fields that we have give (non autogenerated values)

#[derive(Insertable)]
#[diesel(table_name = users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewUser {
    pub name: String,
    pub email: String,
    pub verified: bool,
    pub password: String,
}


#[derive(Insertable)]
#[diesel(table_name = user_email_verifications)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewUserEmailVerifications{
    pub user_email: String,
    pub otp: String,
    pub expires_at: Option<DateTime<Utc>>,
}

#[derive(Insertable)]
#[diesel(table_name = user_reset_pass_validations)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewUserResetPasswordValidation{
    pub user_email : String,
     pub hashed_reset_token : String,
    pub expires_at : Option<DateTime<Utc>>,
}

